apiVersion: skaffold/v1beta13
build:
  artifacts:
  - context: .
    docker:
      dockerfile: Dockerfile
    image: doctorai/ml-pipelines-tfx-custom
  local:
    push: true
    useDockerCLI: true
  tagPolicy:
    envTemplate:
      template: 0.22.0
kind: Config
